// generated by py2many --d=1
import std;

void compare_assert(int a, int b) {
  assert(a == b);
  assert(!(0 == 1));
}

void main(string[] argv) {
  assert(true);
  assert(!(false));
  compare_assert(1, 1);
  assert(true);
  assert(true);
  writeln(format("%s", "OK"));
}
