// generated by py2many --d=1
import std;
import std.algorithm : equal;

void main_func() {
  bool[] ands = [];
  bool[] ors = [];
  bool[] xors = [];
  foreach (a; [false, true]) {
    foreach (b; [false, true]) {
      ands ~= ((a & b));
      ors ~= ((a | b));
      xors ~= ((a ^ b));
    }
  }
  assert(equal(ands, [false, false, false, true]));
  assert(equal(ors, [false, true, true, true]));
  assert(equal(xors, [false, true, true, false]));
  writeln(format("%s", "OK"));
}

void main(string[] argv) {
  main_func();
}
