// generated by py2many --d=1
import std;

void default_builtins() {
  string a = "";
  bool b = false;
  int c = 0;
  double d = 0;
  assert(a == "");
  assert(b == false);
  assert(c == 0);
  assert(d == 0.0);
}

void main(string[] argv) {
  int a = max(1, 2);
  writeln(format("%s", a));
  int b = min(1, 2);
  writeln(format("%s", b));
  int c = min(1.0, 2.0).to!int;
  writeln(format("%s", c));
}
