// generated by py2many --dlang=1
import std;

void default_builtins() {
  const string a = "";
  const bool b = false;
  const int c = 0;
  const double d = 0;
  assert(a == "");
  assert(b == false);
  assert(c == 0);
  assert(d == 0.0);
}

void main(string[] argv) {
  const int a = max(1, 2);
  writeln(format("%s", a));
  const int b = min(1, 2);
  writeln(format("%s", b));
  const int c = min(1.0, 2.0).to!int;
  writeln(format("%s", c));
}
