// generated by py2many --dlang=1
import std;

class Foo {
  ;

  int bar() {
    return baz();
  }

  int baz() {
    return 10;
  }

}

void main(string[] argv) {
  const Foo f = new Foo();
  const b = f.bar();
  writeln(format("%s", b));
  assert(b == 10);
}
