// generated by py2many --dlang=1
import std;

class Foo {
  ;

  string bar() {
    return "a";
  }

}

void main(string[] argv) {
  const Foo f = new Foo();
  const b = f.bar();
  writeln(format("%s", b));
}
