// generated by py2many --dlang=1
import std;
import std.algorithm : equal;
import std.range : iota;
import std.typecons : tuple;

int[] comb_sort(int[] seq) {
  auto gap = seq.length;
  bool swap = true;
  while (gap > 1 || swap) {
    gap = max(1, (gap / 1.25).floor().to!long);
    swap = false;
    foreach (i; iota(0, (seq.length - gap), 1)) {

      if (seq[i] > seq[(i + gap)]) {
        auto __tmp1 = tuple(seq[(i + gap)], seq[i]);
        seq[i] = __tmp1[0];
        seq[(i + gap)] = __tmp1[1];
        swap = true;
      }
    }
  }
  return seq;
}

void main(string[] argv) {
  int[] unsorted = [14, 11, 19, 5, 16, 10, 19, 12, 5, 12];
  const int[] expected = [5, 5, 10, 11, 12, 12, 14, 16, 19, 19];
  assert(equal(comb_sort(unsorted), expected));
  writeln(format("%s", "OK"));
}
