// generated by py2many --dlang=1
import std;

void do_unsupported() {
  const int a = 1;
  /* dict comprehension ((key + 1), (value + 1)) unimplemented on line 9:4 */
  ;
  const bool b = (a != 0);
  writeln(format("%s", b ? ("True") : ("False")));
}

void main(string[] argv) {
  do_unsupported();
}
