// generated by py2many --dlang=1
import std;

void compare_with_integer_variable() {
  const int i = 0;
  int s = 1;

  if (i) {
    s = 2;
  } else {
    s = 3;
  }
  assert(s == 3);
}

void use_zero_for_comparison() {
  const int i = 0;
  int s = 1;

  if (0) {
    s = 2;
  } else {
    s = 3;
  }
  assert(s == 3);
}

void main(string[] argv) {
  compare_with_integer_variable();
  use_zero_for_comparison();
  writeln(format("%s", "OK"));
}
