// generated by py2many --dlang
import std;
import std.algorithm;
import std.array;
import std.range : iota;

void show() {
  auto gen = iota(0, 5, 1).map!(x => (x * x)).array();
  foreach (val; gen) {
    writeln(format("%s", val));
  }
}

void main(string[] argv) {
  show();
}
