// generated by py2many --dlang=1
import std;

int code_0 = 0;
int code_1 = 1;
string code_a = "a";
string code_b = "b";
auto l_b = redBlackTree([code_a]);
int[string] l_c = [code_b: code_0];
void main(string[] argv) {
  assert("a" in l_b);
  writeln(format("%s", "OK"));
}
