// generated by py2many --dlang=1
import std;

const int code_0 = 0;
const int code_1 = 1;
const string code_a = "a";
const string code_b = "b";
const l_b = redBlackTree([code_a]);
const int[string] l_c = [code_b: code_0];
void main(string[] argv) {
  assert("a" in l_b);
  writeln(format("%s", "OK"));
}
