// generated by py2many --dlang=1
import std;
import std.algorithm;

void show() {
  const int a = 1;
  const b = [2, 3].canFind(a) ? (2) : (3);
  writeln(format("%s", b));
}

void main(string[] argv) {
  show();
}
