// generated by py2many --d=1
import std;

void foo() {
  int a = 10;
  int b = 20;
  int _c1 = (a + b);
  int _c2 = (a - b);
  int _c3 = (a * b);
  int _c4 = (a / b);
  int _c5 = -(a);
  double d = 2.0;
  double _e1 = (a + d);
  double _e2 = (a - d);
  double _e3 = (a * d);
  double _e4 = (a / d);
  double _f = -3.0;
  int _g = -(a);
}

int add1(int x, int y) {
  return (x + y);
}

int add2(int x, int y) {
  return (x + y);
}

int add3(int x, int y) {
  return (x + y);
}

int add4(int x, int y) {
  return (x + y);
}

int add5(int x, int y) {
  return (x + y);
}

int add6(int x, int y) {
  return (x + y);
}

int add7(int x, int y) {
  return (x + y);
}

int add8(int x, int y) {
  return (x + y);
}

int add9(int x, int y) {
  return (x + y);
}

int sub(int x, int y) {
  return (x - y);
}

int mul(int x, int y) {
  return (x * y);
}

double fadd1(int x, double y) {
  return (x + y);
}

void show() {
  assert(fadd1(6, 6.0) == 12);
  writeln(format("%s", "OK"));
}

void main(string[] argv) {
  foo();
  show();
}
