// generated by py2many --dlang=1
import std;
import std.range : iota;

void for_with_break() {
  foreach (i; iota(0, 4, 1)) {

    if (i == 2) {
      break;
    }
    writeln(format("%s", i));
  }
}

void for_with_continue() {
  foreach (i; iota(0, 4, 1)) {

    if (i == 2) {
      continue;
    }
    writeln(format("%s", i));
  }
}

void for_with_else() {
  bool has_break = false;
  foreach (i; iota(0, 4, 1)) {
    writeln(format("%s", i));
  }

  if (has_break != true) {
    writeln(format("%s", "OK"));
  }
}

void while_with_break() {
  int i = 0;
  while (true) {

    if (i == 2) {
      break;
    }
    writeln(format("%s", i));
    i += 1;
  }
}

void while_with_continue() {
  int i = 0;
  while (i < 5) {
    i += 1;

    if (i == 2) {
      continue;
    }
    writeln(format("%s", i));
  }
}

void main(string[] argv) {
  for_with_break();
  for_with_continue();
  for_with_else();
  while_with_break();
  while_with_continue();
}
