// generated by py2many --dlang=1
import std;

void show() {
  writeln(format("%s", "b"));
  writeln(format("%s %s", 2, "b"));
  const double a = 2.1;
  writeln(format("%s", a));
  const double b = 2.1;
  writeln(format("%s", b));
  const bool c = true;
  writeln(format("%s", c ? ("True") : ("False")));
}

void main(string[] argv) {
  show();
}
