// generated by py2many --d=1
import std;

void show() {
  writeln(format("%s", "b"));
  writeln(format("%s %s", 2, "b"));
  double a = 2.1;
  writeln(format("%s", a));
  double b = 2.1;
  writeln(format("%s", b));
  bool c = true;
  writeln(format("%s", c ? ("True") : ("False")));
}

void main(string[] argv) {
  show();
}
