// generated by py2many --d=1
import std;

/* This file implements a rectangle class  */

class Rectangle {
  int height;
  int length;

  this(int height, int length) {
    this.height = height;
    this.length = length;
  }

  bool is_square() {
    return height == length;
  }

}

void show() {
  Rectangle r = new Rectangle(1, 1);
  assert(r.is_square());
  r = new Rectangle(1, 2);
  assert(!(r.is_square()));
  writeln(format("%s", r.height));
  writeln(format("%s", r.length));
}

void main(string[] argv) {
  show();
}
