#= Manages a dictionary of CLSID strings to Python classes.

Primary use of this module is to allow modules generated by
makepy.py to share classes.  @makepy@ automatically generates code
which interacts with this module.  You should never need to reference
this module directly.

This module only provides support for modules which have been previously
been imported.  The gencache module provides some support for loading modules
on demand - once done, this module supports it...

As an example, the MSACCESS.TLB type library makes reference to the
CLSID of the Database object, as defined in DAO3032.DLL.  This
allows code using the MSAccess wrapper to natively use Databases.

This obviously applies to all cooperating objects, not just DAO and
Access.
 =#
mapCLSIDToClass = Dict()
function RegisterCLSID(clsid, pythonClass)
    mapCLSIDToClass[string(clsid)] = pythonClass
end

function RegisterCLSIDsFromDict(dict)
    update(mapCLSIDToClass, dict)
end

function GetClass(clsid)::Dict
    return mapCLSIDToClass[clsid]
end

function HasClass(clsid)::Bool
    return clsid in mapCLSIDToClass
end
